version: '3.8'
services:
  mongo:
    image: mongo:7
    container_name: mongo-st
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: speech_therapy
    volumes:
      - mongo-data:/data/db
      - ./docker/mongo/init:/docker-entrypoint-initdb.d:ro
volumes:
  mongo-data:
